services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Koboldsoft\PdfFormFillerBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Resources,Pdfs}'
